version: "3.7"

services:

    redis:
        image: redis
        ports:
            - 6379:6379
        volumes:
            - am180-redis:/data
        restart: always

    postgres:
        depends_on:
            - redis
        image: postgres
        secrets:
            - postgres-user
            - postgres-password
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_USER_FILE/run/secrets/postgres-user
            - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
        ports:
            - 5432:5432
        volumes:
            - am180-postgres:/var/lib/postgresql/data
        restart: always

    web:
        depends_on:
            - redis
            - postgres
        build:
            context: .
            dockerfile: etc/docker/web-release.Dockerfile
        secrets:
            - azure-appconfig
        environment:
            - APPLICATION__AZUREOPTIONS__APPCONFIG=/run/secrets/azure-appconfig
        expose:
            - 5000
        restart: always

    nginx:
        depends_on:
            - web
        build:
            context: .
            dockerfile: etc/docker/nginx-release.Dockerfile
        ports:
            - 80:80
            - 443:443
        volumes:
            - am180-ssl:/etc/letsencrypt
        restart: always

secrets:

    postgres-user:
        file: secrets/postgres-user
    postgres-password:
        file: secrets/postgres-password
    azure-appconfig:
        file: secrets/azure-appconfig

volumes:

    am180-redis:
        external: true
    am180-postgres:
        external: true
    am180-ssl:
        external: true
